### PR TITLE
[Feature request] Ability to use custom template for step

### PR DESCRIPTION
**Pull request by rabingaire**
#3

### CODE REVIEW

**Comment by rabingaire** [comment]
```
<step-indicator
  :handleClick="handleClick"
  :current="current"
  :total="total"
  :current-color="currentColor"
  :default-color="defaultColor"
>
  <div class="someOtherStyle" />
</step-indicator>
```
The API is implemented like this, for now, the styled passed inside `div` is a user-defined style which enables them to customize the UI as per their requirement. Guys do give suggestions and brainstorm about how well can we define the API. I am always happy to contribute. Happy Coding !!!

**Comment by egoist** [comment]
Hmm why is it designed to use the `children` instead of `props`? 🤔

**Comment by rabingaire** [comment]
We can do that but class or id passed as porps is also implemented on step-indicator as well and we don't want same style on parent and child elements so I used children if you find this bad idea let's discuss about the API

**Comment by sqal** [comment]
I think these changes are not what OP in #3 asked for. I also wonder why did you choose to use `children` instead of using scoped slots for this. Imho it's so much easier to implement this with scoped slots. Also your current changes doesn't actually allow to use custom template What if I want to do something like this:

```
<div>
  <h4>Some text</h4>
  <span>{{ step }}</span>
</div>
```

It's not possible because you always override step element content (line 42).  I'm too lazy today to send PR but i made quick demo with new implementation  https://jsfiddle.net/r95vx0sx/

**Pull request closed without merging**
